name: test

on: workflow_call

jobs:
  # ✅ 只保留这个，正常执行
  build-oneplus-8-series-oos13-a13-xtd:
    uses: ./.github/workflows/build-oneplus-8-series-oos13-a13-xtd.yml
    secrets: inherit

  # ❌ 以下全部跳过
  build-oneplus-8-series-cos15-a15:
    if: false
    uses: ./.github/workflows/build-oneplus-8-series-cos15-a15.yml
    secrets: inherit

  build-xiaomi-mix2s-evox10-a15:
    if: false
    uses: ./.github/workflows/build-xiaomi-mix2s-evox10-a15.yml
    secrets: inherit

  build-xiaomi-mix2s-aosp-a16-419:
    if: false
    uses: ./.github/workflows/build-xiaomi-mix2s-aosp-a16-419.yml
    secrets: inherit

  build-xiaomi-11-evox-a16:
    if: false
    uses: ./.github/workflows/build-xiaomi-11-evox-a16.yml
    secrets: inherit

  build-xiaomi-mipad4-lineageos22-a15:
    if: false
    uses: ./.github/workflows/build-xiaomi-mipad4-lineageos22-a15.yml
    secrets: inherit

  build-redmi-k20pro-aosp-a15-sovietstaross:
    if: false
    uses: ./.github/workflows/build-redmi-k20pro-aosp-a15-sovietstaross.yml
    secrets: inherit

  build-redmi-8-aosp-a15-419:
    if: false
    uses: ./.github/workflows/build-redmi-8-aosp-a15-419.yml
    secrets: inherit

  build-redmi-note7-aosp-a15:
    if: false
    uses: ./.github/workflows/build-redmi-note7-aosp-a15.yml
    secrets: inherit

  build-redmi-note11pro-5g-aosp-a16:
    if: false
    uses: ./.github/workflows/build-redmi-note11pro-5g-aosp-a16.yml
    secrets: inherit

  build-samsung-note10-oneui-a15:
    if: false
    uses: ./.github/workflows/build-samsung-note10-oneui-a15.yml
    secrets: inherit

  build-samsung-note10plus-oneui-a15:
    if: false
    uses: ./.github/workflows/build-samsung-note10plus-oneui-a15.yml
    secrets: inherit

  build-samsung-a71-aosp-a16:
    if: false
    uses: ./.github/workflows/build-samsung-a71-aosp-a16.yml
    secrets: inherit

  build-samsung-a71-oneui-a16:
    if: false
    uses: ./.github/workflows/build-samsung-a71-oneui-a16.yml
    secrets: inherit

  build-nothing-phone-1-lineageos23-a16:
    if: false
    uses: ./.github/workflows/build-nothing-phone-1-lineageos23-a16.yml
    secrets: inherit

  build-smartisan-u3pro-lineageos18-a11:
    if: false
    uses: ./.github/workflows/build-smartisan-u3pro-lineageos18-a11.yml
    secrets: inherit
